INSERT INTO authorities (username, authority)
VALUES  ('Jacquelien', 'ROLE_ADMIN'),
        ('Bets', 'ROLE_MODERATOR'),
        ('Karel', 'ROLE_USER');

INSERT INTO users (username, email, password, apikey)
VALUES ('Jacquelien', 'jdoudhoff@fictional.nl', '$2a$12$vL/WjHUF7ZL5bYDQNfCkS.C.eKpd/xZlAzAgeO5ItC9kNBHyajzbW', '514270'),
       ('Bets', 'betsreader@fictional.nl', '$2a$12$rCZi4UIXPtrNdQdSfelAcOwweREMl4.AddVv3WOKvl.2U4dIWta9K', '213274'),
       ('Karel', 'koudhoff@fictional.nl', '$2a$12$/bn9V1Rs3ddYvJaqu10QwO/oU3BIiWpYtPzutAdz29dGilUSKQSou', '316270');

INSERT INTO books(id, title, author, original_title, released, movie_adaptation, description)
        VALUES (1, 'Carrie', 'Stephen King', 'Carrie', 1974, 'Carrie 1976 - 2013', 'Het verhaal gaat over Carrie, een zeventienjarig meisje met telekinetische gaven. Ze is een buitenbeentje op school en wordt vaak gepest en vernederd, ook door haar dominante moeder. Maar ze ontdekt haar krachten en krijgt deze steeds meer onder controle. Op het schoolbal gaan haar klasgenoten te ver en neemt Carrie wraak...'),
        (2, 'Bezeten Stad', 'Stephen King', 'Salems Lot', '1975', 'Salems Lot 1979 - 2004', 'Ben Mears was pas zeven jaar toen hij zijn geboortestadje ''Salem''s Lot'' verliet. Nu, vijfentwintig jaar later, is hij teruggekomen om de waarheid bloot te leggen. De waarheid over de geheimzinnige verdwijningen, de spookverhalen en de geestesverschijningen. Maar niemand wist dat er ook een vreemdeling was gekomen, iemand die een geheim met zich droeg dat zo oud was als de wereld. Zij die hij aanraakte zouden sterven, met al degenen die zij liefhebben. Alles zou voor altijd veranderen. Voor Susan, die niet beschermd kon worden door haar liefde voor Ben. Voor Vader Callahan, de priester die zijn geloof aan een laatste proef onderwierp. En voor Mark, een kleine jongen die zijn fantasiewereld werkelijkheid ziet worden. Toch blijkt juist hij het beste in staat de huiveringwekkende nachtmerrie van ''Salem''s Lot'' het hoofd te bieden.'),
        (3, 'De shining', 'Stephen King', 'The shining', '1977', 'The Shining 1980 - 1997', 'Het verhaal speelt zich af in het verlaten Overlook Hotel ergens in de Rocky Mountains, waar schrijver Jack Torrance, zijn vrouw Wendy en hun zoontje Danny huismeesters zijn. Danny is helderziend en voorziet het gevaar, de spoken van het verleden komen in het hotel opnieuw tot leven. Jack merkt dit ook en het hotel drijft hem tot waanzin. Dit leidt ertoe dat Wendy en Danny, omsloten door sneeuw, ver van de buitenwereld, opgesloten zitten met een levensgevaarlijke gek.'),
        (4, 'Satanskinderen', 'Stephen King', 'Night shift', '1978', 'Bijna alle verhalen zijn verfilmd', 'Verhalenbundel met 19 verhalen'),
        (5, 'De Beproeving', 'Stephen King', 'The Stand', '1978', 'The Stand 1994 - 2023', 'Het stof vormde een nauwelijks doorzichtige waas dat het stadje Arnette het aanzien van een spookstad gaf: in de hoofdstraat lagen soldaten en honden naast elkaar in de goot: onbeweeglijk, dood. Zelfs de zon liet Arnette in de steek en het stadje verduisterde onder de vleugels van de nacht... De Grote Plaag is voorbij. Het land blijft vrijwel ontvolkt achter. De schaarse overlevenden halen even opgelucht adem; maar niet voor lang. Niemand kon de beproeving voorzien die eenieder dwingt een keuze te maken tussen voor of tegen, tussen goed of kwaad. In een meedogenloze strijd die het verloop van de toekomst voorgoed zal bepalen staan twee machten verbeten tegenover elkaar..'),
        (6, 'Dodelijk dilemma', 'Stephen King', 'The dead zone', '1979', 'The dead zone 2002', 'John Smith, een jonge leraar, raakt betrokken bij een fataal auto-ongeluk en ligt 4,5 jaar in coma. Zijn vriendin en familie hebben alle hoop opgegeven, het leven gaat door. Maar het ongelooflijke geschiedt, John Smith opent zijn ogen en na een langdurige therapie kan hij het ziekenhuis verlaten. Er is echter het een en ander veranderd, hij merkt dat hij een voorspellende gave heeft, speciaal wanneer hij mensen aanraakt. Dit inzicht in de toekomst heeft een werkelijk dramatische invloed op zijn nabije omgeving en leidt tot een gewelddadige climax...'),
        (7, 'Ogen van vuur', 'Stephen King', 'Firestarter', '1980', 'Firestarter 1984 - 2022', 'Andy McGee en Vicky Tomlinson stellen zich vrijwillig beschikbaar voor een experiment met een volslagen onbekende drug, bedacht en ontwikkeld door een bizar regeringsbureau, in kleine kring bekend als ''De Winkel''. Hun dochtertje Charlie slaagt er twee jaar later in haar teddybeer in brand te laten vliegen... slechts door ernaar te kijken. Een vreeswekkende waarheid openbaart zich: Charlie is pyrokinetisch begaafd en kan met haar blik zelfs mensen in vlam zetten. ''De Winkel'' stelt alles in het werk om Charlie te kidnappen. Als dat gelukt is, dwingen zij Charlie haar gruwelijke gave maximaal te ontwikkelen. Eén ding vergeten zij echter. Hun dwang werkt averechts... Langzaam elimineert Charlie haar gevoelens tot een diepgeworteld verlangen overblijft: wraak!');
